export const masterChallengesList = [
  // ... (daftar tantangan Anda tetap di sini)
  { id: "syukurPagi", category: "Kesadaran diri", title: "Syukur Pagi", description: "Tulis 3 hal yang kamu syukuri hari ini-Berterimakasihlah kepada Sang Pencipta .", imageUrl: "https://images.unsplash.com/photo-1549032305-e816fabf0dd2?w=600&auto=format&fit=crop&q=60" },
  { id: "meditasi5Menit", category: "Kesadaran diri", title: "Meditasi 5 Menit", description: "Luangkan 5 menit untuk duduk tenang, fokus pada napas Anda.", imageUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&auto=format&fit=crop&q=60" },
  { id: "bergerak20Menit", category: "Self-Care", title: "Bergerak Aktif 20 Menit", description: "Lakukan aktivitas fisik ringan selama 20 menit.", imageUrl: "https://images.unsplash.com/photo-1661251626004-e771af28d113?q=80&w=2042&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
  { id: "hubungiTeman", category: "Sosial", title: "Hubungi Seorang Teman", description: "Sapa seorang teman atau keluarga yang lama tak berkabar.", imageUrl: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?w=600&auto=format&fit=crop&q=60" },
  { id: "refleksiKebiasaanDigital", category: "Refleksi-diri", title: "Refleksi Kebiasaan Digital", description: "Luangkan 15 menit untuk refleksi: Adakah kebiasaan online (mis. game, media sosial, atau judi) yang terasa mengganggu mood atau menyita waktumu? Pikirkan satu aktivitas positif penggantinya atau tanyakan ke fitur ChatAI.", imageUrl: "https://images.unsplash.com/photo-1509029032154-54ba8b3216d4?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
  { id: "hobiKreatif30Menit", category: "Kreatifitas", title: "Dedikasikan 30 Menit untuk Hobi Kreatif", description: "Melukis, menulis, bermain musik, atau kerajinan tangan. Alihkan energi ke sesuatu yang membangun.", imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600&auto=format&fit=crop&q=60" },
  { id: "rencanakanKeuanganMingguan", category: "Kesehatan Keuangan", title: "Rencanakan Keuangan Mingguan", description: "Catat pengeluaran, buat anggaran sederhana, atau tetapkan satu tujuan finansial kecil minggu ini. Kesadaran finansial adalah kunci.", imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&auto=format&fit=crop&q=60" },
  { id: "jedaNotifikasi1Jam", category: "Kesejahteraan Digital", title: "Jeda Notifikasi Selama 1 Jam", description: "Matikan notifikasi media sosial dan aplikasi tidak penting selama satu jam untuk fokus atau relaksasi.", imageUrl: "https://images.unsplash.com/photo-1584091377126-3817650725fc?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
  { id: "nikmatiAlam15Menit", category: "Grounding", title: "Nikmati Alam Sekitar 15 Menit", description: "Duduk di taman, perhatikan awan, atau dengarkan suara alam. Terhubung kembali dengan lingkungan.", imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&auto=format&fit=crop&q=60" },
  { id: "pelajariSatuHalBaru", category: "Growth-Mindset", title: "Pelajari Satu Hal Baru Hari Ini", description: "Baca artikel, tonton video edukasi, atau pelajari satu kata baru. Perluas wawasanmu.", imageUrl: "https://images.unsplash.com/photo-1491841550275-ad7854e35ca6?w=600&auto=format&fit=crop&q=60" },
  { id: "tulis3AfirmasiPositif", category: "Self-Love", title: "Tulis 3 Kalimat Afirmasi Positif", description: "Fokus pada kekuatan dan hal baik tentang dirimu. Ucapkan dengan yakin.", imageUrl: "https://plus.unsplash.com/premium_photo-1664444320083-3c0458bcc2b5?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
  { id: "lakukanSatuKebaikanKecil", category: "Kebaikan", title: "Lakukan Satu Kebaikan Kecil", description: "Bantu seseorang, berikan pujian tulus, atau donasi kecil. Memberi juga membahagiakan.", imageUrl: "https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?w=600&auto=format&fit=crop&q=60" },
  { id: "identifikasiPemicuEmosi", category: "Self-Awareness", title: "Kenali Satu Pemicu Emosi Negatif", description: "Apa yang membuatmu stres atau cemas hari ini? Sadari dan pikirkan cara meresponsnya dengan lebih sehat.", imageUrl: "https://images.unsplash.com/photo-1618910300977-e95eed561bed?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
  { id: "evaluasiPenggunaanAplikasi", category: "Kesejahteraan Digital", title: "Evaluasi Penggunaan Satu Aplikasi", description: "Pilih satu aplikasi yang sering kamu gunakan. Apakah memberimu manfaat atau justru sebaliknya? Pertimbangkan untuk mengurangi penggunaannya jika perlu.", imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600&auto=format&fit=crop&q=60" },
  { id: "rencanakanAktivitasOffline", category: "Sosial", title: "Rencanakan Aktivitas Offline Menyenangkan", description: "Jadwalkan bertemu teman, mengunjungi tempat baru, atau melakukan olahraga di luar rumah untuk akhir pekan.", imageUrl: "https://plus.unsplash.com/premium_photo-1666184130709-f3709060899a?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" },
];